ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQUdTB4LywxuuVxPZDoS+TfjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUxMjExMDcwODE3WhcNMzUx
  MjA5MDcwODE3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJeJVN8afSI4dk6wkrAbMFlE78S3OP280Z
  /vo44uQ5LeDP66p1YuZ9iUKKjlZLGJNHxCfbgt9sQ0sT3VJuroMhyMh3f0fku4Mw
  n4Th9wWovY4KCpO4eAc+F64WaED5hF13Zc1LZfnj+f5rBPwkyxC1AL3UttIZejen
  cST4vQs+17L6EyFyCijqOCq53ME17RcwDXAeJMBUK04IQNJmIuvi2/0AktnYUOZ0
  SF/59vIpNYpYTQVGR+erj3mF7tY1wDyGAF+v+CHD6YGpYOqkrcXxsxn1pz1Ps4TL
  obROEERNjtxoAxfbF1wPhI9MpsZAVy56vQZbB3Uycq/VDW9WcycrAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTS5BR+EYoCUMA7dti6uQDJ/khU
  fzAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAk0utlHaLEtRBmdBbT85CQc5kbUbwLcymS699tumErhXx
  oJeWJJR8crsAVgGBNrUW5E2yQtfXHQUmfGD9RwJQ8CpP6JMkq3NSp0bSp9vP62UF
  kuU+HXo+/sCpAJC37BSMi0dqrBu+lF/n0rFvM69P8wCleBgcub85KTxD5lqKR8+z
  N77RLpEJsU/5gmNThtaW/wVYWD85MR+mvt8X5icB9OtFgCPa5fUbSLO/19yiKYNg
  9xLiEY5mPZlLx1k7lnp8MR3KoTXsO1dH876QlOl3Ct36i6ip7Tk2GeBAM2ZBfRVk
  WqTrL/376V7DSyYg9VA+xGLCmsuyyOcmxnxcEmTjlg==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDOTCCAiGgAwIBAgIQdy4GGba8nlqsfrXhxA/zCjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUxMjE0MDczMjI4WhcNMjYx
  MjE0MDczMjI4WjAlMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDDAKBgNVBAMTA2Fw
  aTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALeV2Pp5sWuu07pXxLXk
  /t9E8sFEvsPZhE4CkWIF7kDh5moXMJhtgyweAWeOXiJua9+lveOELlfdaMFxfU0S
  5DOZv2hKe53BMgozpPSOKSEQDsx4I51bEf06rLmzC+KKNTvuUPQ+yaVA2cr/8xl/
  buZl8vkUHfWryScDo8eDM4lEk02PeN1CKxF8CooKPGWUqlrPb1fAC90nNnUcrKGx
  qljiwuS2hZlNXE1UA3SVdE4jAGm8K3AUCS6E9blRMZ2O6WQk+V1ikUV2nD+qLGhA
  JLFUSonjl6udWvnbqK4O02+ubl/LJ8Qzg2omNMjk/2s+ezj+UbGUE2KTIFLFyVRm
  i/ECAwEAAaNwMG4wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
  BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFNLkFH4RigJQwDt2
  2Lq5AMn+SFR/MA4GA1UdEQQHMAWCA2FwaTANBgkqhkiG9w0BAQsFAAOCAQEAE9sW
  k8d9mfr0swROO9YARqbnL/hBGHRssZCuAmzPKQT1so0I9VY7hwAYmX7Usr16uQSw
  /iAtboQ3UtoVHDuGsLnp/o1/h0VJvUtWENo5xe5LB0kwRAQoldkNq3pevjJ88LMa
  xMO+Vta9p+NbrRl1EePkdCsDDKlzsbltUzsOdqRZwaCWra2pbZB7nsCQR8UWFk6g
  LZCRFU6gXezyXILHonh2hWcerR3+81Iz8OaKCLbHrBQ7o64DUbeipovhBjI6rlMP
  i+/iFlOGvHcprkwTkjrCz1ryc5GYwWVerrfcAzV6B2JsLd+7/73JHovMjBUqvb/H
  Iy1ztMWVDKUXgzwYxA==
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEAt5XY+nmxa67TulfEteT+30TywUS+w9mETgKRYgXuQOHmahcw
  mG2DLB4BZ45eIm5r36W944QuV91owXF9TRLkM5m/aEp7ncEyCjOk9I4pIRAOzHgj
  nVsR/TqsubML4oo1O+5Q9D7JpUDZyv/zGX9u5mXy+RQd9avJJwOjx4MziUSTTY94
  3UIrEXwKigo8ZZSqWs9vV8AL3Sc2dRysobGqWOLC5LaFmU1cTVQDdJV0TiMAabwr
  cBQJLoT1uVExnY7pZCT5XWKRRXacP6osaEAksVRKieOXq51a+duorg7Tb65uX8sn
  xDODaiY0yOT/az57OP5RsZQTYpMgUsXJVGaL8QIDAQABAoIBAAUdaj7iyXkdhSnE
  wJ7cgScjdLPCrIG4h4uUndw2O/bP8G9x41VI3lHqKVn7NQdWrh/cXl22mOOy8BRt
  Kvt88HGZWdRQGHD7ES/Ic/LqG85fdBkZaw0bHKWCdy3ilZz/gqePfo8KiYvWkmbZ
  8hoKk1J9IkuTJllKGqvxCZTxRGwhakHlMP7mqhdfvH4LgFhHLdAjYYHRDNrH+7AQ
  vAYHL8DykftriBRMS0hqdFBAQqs+1TQXmX983ZD9AWdIWlg+6Mx40Mody99AdSrs
  bfFfqq6oWwuBJlDTPpKWMIr7A/mSwJxwDTfQAGthbE7SE8DTswY2exCV71JXKsQ6
  o0gGkeECgYEA9JlYvHVYf4uT1h+GacTNSasDC0rMdlxM/XSAWOG+qFtyUxK0hvrJ
  1ybL0zQsU9x5pcSa4UxN1u9Wx4AlCsWkWYYDs0tBQAvOB83qWJnftEMshuIaD4v/
  8zVaesofJDu+EsNR2GND9g2AOJE7FdyUT+Bc5J7SxLmlJmZIttAnGlECgYEAwCR2
  H13kZV92m3pHnxmGP/dn2HymPRX4n+Lj1c/Ht0mROAe0Bl8pBGXubMXEdAeiMYPZ
  1da3okwjlY46+BBAJieP721CFRSiTvA3I/NN9+8OlBFU/x1avHJsZMgoybKG5DGg
  PPPPcJEh3L40H6LXynYiNNoLILkAd8mBClOwT6ECgYAvoIBXyd2ekDYMFn1csPZs
  JsFj/H+NeHGBVKL9K4+tRokfReAi/Eg6/ZHooRsUhTSmo36o6euqM1ZJaFlOHKfg
  yqiDy957sxC+EklUUTnu5rmP1gzPBCqlV7kzeZHQw1VCYAfaw5FjIsPZv+WqXxX9
  66kK1yYhKijPLlFwT12d0QKBgBIFmXq5sMl9Wb+diYg3uarYRso8bs8991Lv0hTk
  50Oex9sshcsvM8aw1Nso9ZM4gBMK3ey7tf+oCpJlg8xuocWyYkK/ybn2dH7Y8yMR
  GBgQORrUQVeoZjFUviv5xjGc6CARM4lkCOnzAu0UfgkVmg3oZK72YKLSF2Qk51CT
  pu7hAoGAOTaAtZhkOn86dffB7bDH20L1Zh/UjXts14Ootj5VW/KS3gjDnmoJzfSn
  pEffjsNg9JJ3Obe7q0bPw6s19O6SvN6aFNYVqkbGyJCTZE4PvDyUjdfxSSL7fbEP
  m3bHPjgLh4BoU5WtnhP/oQSVrCtdrtq3dHg5QmsYxFyFKZgbYzg=
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8001
name: api
